// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateUserInput struct {
	Name string `json:"name"`
	Age  int    `json:"age"`
}

type Mutation struct {
}

type Post struct {
	Ulid    string `json:"ulid"`
	Title   string `json:"title"`
	Content string `json:"content"`
}

type Query struct {
}

type UpdateUserInput struct {
	Name *string `json:"name,omitempty"`
	Age  *int    `json:"age,omitempty"`
}

type User struct {
	Ulid string `json:"ulid"`
	Name string `json:"name"`
	Age  int    `json:"age"`
}
